pc_fisherz_005:
    algorithm_name: pc
    algorithm_params:
        alpha: 0.05
        indep_test: fisherz

pc_fisherz_01:
    algorithm_name: pc
    algorithm_params:
        alpha: 0.1
        indep_test: fisherz

pc_kcigaussian_005:
    algorithm_name: pc
    algorithm_params:
        alpha: 0.05
        indep_test: fastkci

pc_kcigaussian_01:
    algorithm_name: pc
    algorithm_params:
        alpha: 0.1
        indep_test: fastkci

fci_fisherz_005:
    algorithm_name: fci
    algorithm_params:
        alpha: 0.05
        indep_test: fisherz

fci_fisherz_01:
    algorithm_name: fci
    algorithm_params:
        alpha: 0.1
        indep_test: fisherz

fci_kcigaussian_005:
    algorithm_name: fci
    algorithm_params:
        alpha: 0.05
        indep_test: kci

fci_kcigaussian_01:
    algorithm_name: fci
    algorithm_params:
        alpha: 0.1
        indep_test: kci

ges_bic:
    algorithm_name: ges
    algorithm_params:
        score_func: local_score_BIC

ges_bdeu:
    algorithm_name: ges
    algorithm_params:
        score_func: local_score_BDeu

ges_margigeneral:
    algorithm_name: ges
    algorithm_params:
        score_func: local_score_marginal_general

ges_margimulti:
    algorithm_name: ges
    algorithm_params:
        score_func: local_score_marginal_multi

grasp_bic:
    algorithm_name: grasp
    algorithm_params:
        score_func: local_score_BIC

grasp_bdeu:
    algorithm_name: grasp
    algorithm_params:
        score_func: local_score_BDeu

grasp_margigeneral:
    algorithm_name: grasp
    algorithm_params:
        score_func: local_score_marginal_general

grasp_margimulti:
    algorithm_name: grasp
    algorithm_params:
        score_func: local_score_marginal_multi
        
boss_bic:
    algorithm_name: boss
    algorithm_params:
        score_func: local_score_BIC

boss_bdeu:
    algorithm_name: boss
    algorithm_params:
        score_func: local_score_BDeu

boss_margigeneral:
    algorithm_name: boss
    algorithm_params:
        score_func: local_score_marginal_general

boss_margimulti:
    algorithm_name: boss
    algorithm_params:
        score_func: local_score_marginal_multi
        
directlingam_pwling:
    algorithm_name: directlingam
    algorithm_params:
        measure: pwling

directlingam_kernel:
    algorithm_name: directlingam
    algorithm_params:
        measure: kernel

# notears_default:
#     algorithm_name: notears
#     algorithm_params:
#         lambda1: 0.01
#         loss_type: l2
#         max_iter: 100
#         h_tol: 1e-8
#         rho_max: 1e+16
#         w_threshold: 0.3

# dag_gnn_default:
#     algorithm_name: dag_gnn
#     algorithm_params:
#         device_type: gpu

# corl_default:
#     algorithm_name: corl
#     algorithm_params:
#         device_type: gpu

# notears_default:
#     algorithm_name: notears
#     algorithm_params:

# grandag_default:
#     algorithm_name: grandag
#     algorithm_params:
#         device_type: gpu
