algorithm_name: run_boss
algorithm_params:
    num_starts: 1
    use_bes: false
    time_lag: 0
    use_data_order: true
    output_cpdag: true
score_name: use_degenerate_gaussian_score
score_params:
    penalty_discount: 1
    structure_prior: 0
    singularity_lambda: 0.0
bootstrap_params:
    numberResampling: 10 # numberResampling=0 -> No bootstrapping
    percent_resample_size: 100
    add_original: true
    with_replacement: true
    resampling_ensemble: 3
    seed: -1
num_threads: 16