algorithm_name: run_direct_lingam
score_name: use_degenerate_gaussian_score
score_params:
    penalty_discount: 1
    structure_prior: 0
    singularity_lambda: 0.0
bootstrap_params:
    numberResampling: 10 # numberResampling=0 -> No bootstrapping
    percent_resample_size: 100
    add_original: true
    with_replacement: true
    resampling_ensemble: 3
    seed: -1
num_threads: 16